FROM debian:10

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

COPY my.cnf /etc/mysql/my.cnf
COPY entrypoint.sh .

RUN mkdir -p /run/mysqld;\
    chown -R mysql:mysql /run/mysqld;\
    chown -R mysql:mysql /var/lib/mysql;\
    mysql_install_db --basedir=/usr --user=$MYSQL_USER --datadir=/var/lib/mysql;\
    chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

CMD ["mysqld"]
